### ISSUE TITLE
feat: 部署多样化

### ISSUE THREAD

**Issue by real-jiakai** [simple-is-awesome/simple#19]
国内私有化部署优先，国外paas部署优先。

vps部署：docker compose解决
vercel、netlify部署，点击一键部署按钮，设置环境变量即可。

**Comment by real-jiakai** [comment]
~~需将supabase尽快集成进docker-compose.yml文件中。~~

supabase的docker-compose.yml文件总共有300多行，添加进nextjs项目的docker-compose.yml，会增加部署系统的复杂度，因此我选择将两者分开部署。

可能会有人疑惑，为啥一定要使用docker部署呢？请见chatgpt4的回答：
![image](https://user-images.githubusercontent.com/82650452/233837156-a2645425-e940-42de-aae4-8c2109980c5c.png)

**Comment by real-jiakai** [comment]
nextjs应用打包成docker镜像，实现Build Once, Deploy Anywhere!的愿景失败了。
在next.js中环境变量在构建docker镜像时，以`NEXT_PUBLIC_`开头的环境变量会被内联至docker镜像中，因此会造成docker-compose.yml同级目录下的`.env`文件就算加载进了容器，但也不能对nextjs项目起作用的窘境。

虽然国外网友提出了诸如使用entrypoint.sh的方法（在容器运行前初始化容器的运行环境）。但是在我尝试的过程中出现了有部分环境变量被初始化成功，有一部分还是原样的场景（捣鼓了1天，依旧没有解决这个问题），于是最终我删除了dockerhub上的镜像，以及github action打包nextjs为docker镜像，自动上传至dockerhub的yaml文件。选择了本地构建镜像，本地部署的方法。

参考资料：

- [Runtime Environment Variables in Next.js](https://notes.dt.in.th/NextRuntimeEnv)
- [Docs: Environment variables documentation implies they're always read at build time #39299](https://github.com/vercel/next.js/issues/39299)
- [docker image with NEXT_PUBLIC_ env variables #17641](https://github.com/vercel/next.js/discussions/17641)
- [nextjs-docker-runtime-env](https://github.com/CopyJosh/nextjs-docker-runtime-env)
- [Buildtime vs runtime environment variables with Next.js and Docker](https://www.saltycrane.com/blog/2021/04/buildtime-vs-runtime-environment-variables-nextjs-docker/)

**Comment by real-jiakai** [comment]
构建docker的参考资料：

- [What is the best way to use NextJS with docker? #16995](https://github.com/vercel/next.js/discussions/16995)

**Comment by real-jiakai** [comment]
netlify部署动态路由404参考资料：

- [[Bug]: 404 page for static routes using getStatic... #2043](https://github.com/netlify/next-runtime/issues/2043)
- [NextJS Routes 404 on Successful Build](https://answers.netlify.com/t/nextjs-routes-404-on-successful-build/89630)

**Comment by alianza** [comment]
https://github.com/netlify/next-runtime/issues/2043 Seems to be fixed. I redeployed my site that was experiencing issues and everything is working again. (Prerendered dynamic routes)

**Comment by real-jiakai** [comment]
> [netlify/next-runtime#2043](https://github.com/netlify/next-runtime/issues/2043) Seems to be fixed. I redeployed my site that was experiencing issues and everything is working again. (Prerendered dynamic routes)

Yes, I redeployed my next.js app in netlify and the dynamic routes show normal. [Netlify Nextjs Demo](https://ntl-demo.njxzc.top/)

The working efficiency of next-runtime project's developers is amazing.
